"""empty message

Revision ID: 7b115c9ec4d8
Revises: 
Create Date: 2020-05-24 00:32:54.172877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b115c9ec4d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('movies_title_key', 'movies', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('movies_title_key', 'movies', ['title'])
    # ### end Alembic commands ###
